### ISSUE TITLE
Showing SQL connections in "Statistics sql"

### ISSUE THREAD

**Issue by MiguelAngel82** [javamelody/grails-melody-plugin#56]
Hi everyone.

I've been trying the plugin with a simple Grails 3 app but I cannot see SQL statistics by default when I access to "monitoring" page.

I've tried some suggested workarounds like [this](https://stackoverflow.com/questions/9809805/grails-melody-plugin-no-longer-logs-sql-calls-as-of-grails-2-0) and [that](http://dmitrijs.artjomenko.com/2012/09/javamelody-sql-monitoring-with-grails.html), but it doesn't work. For the last suggestiond I've tried this piece of code, in `build.gradle`:

```
bootRun {
    jvmArgs('-Djavamelody.datasources=java:comp/env/jdbc/dataSource')
    addResources = true
}
```
But it doesn't work. Maybe I've made some mistake, because showing JavaMelody log I can see this:

```
Sun Mar 11 20:03:37 CET 2018     DEBUG     JavaMelody listener init started
Sun Mar 11 20:03:37 CET 2018     DEBUG     rebinding datasources failed, skipping
```
Probably, all of this is related to the issue ["JDBC DataSource is not wrapped, SQL requests are not monitored"](https://github.com/javamelody/grails-melody-plugin/issues/3). If so, please, let me know what I'm doing wrong because, by default, it does not show SQL statistics.

Thank you very much.

Kind regards,
Miguel.

**Comment by MiguelAngel82** [comment]
This responds myself:

Looking on the [JDBC JavaMelody documentation](https://github.com/javamelody/javamelody/wiki/UserGuide#7-jdbc), I've seen that if you add the driver class to `net.bull.javamelody.JdbcDriver` it works. So this configuration, in `application.yml` works:

```
dataSource:
    [...]
    driverClassName: net.bull.javamelody.JdbcDriver
   [...]

environments:
    development:
        dataSource:
            dbCreate: create-drop
            url: jdbc:mysql://localhost:3306/test?driver=com.mysql.jdbc.Driver
```

But I'm not sure if this is the best approach or it could work with the `javamelody.datasources` property mentioned before.
